const PROGRESIONES_DATA = (() => {
    "use strict";

    const basicas = [
    {
        "id": "I-IV-V-I",
        "nombre": "I - IV - V - I",
        "searchId": "I - IV - V - I"
    },
    {
        "id": "ii-V-I",
        "nombre": "ii - V - I",
        "searchId": "ii - V - I"
    },
    {
        "id": "I-vi-IV-V",
        "nombre": "Círculo de 50s (I-vi-IV-V)",
        "searchId": "I - vi - IV - V"
    },
    {
        "id": "vi-IV-I-V",
        "nombre": "Pop (vi-IV-I-V)",
        "searchId": "vi - IV - I - V"
    },
    {
        "id": "I-V-vi-IV",
        "nombre": "Pop Alternativo (I-V-vi-IV)",
        "searchId": "I - V - vi - IV"
    },
    {
        "id": "ii-V-I-vi",
        "nombre": "ii - V - I - vi",
        "searchId": "ii - V - I - vi"
    },
    {
        "id": "I-IV-vii-iii-vi-ii-V-I",
        "nombre": "Círculo de Quintas Diatónico",
        "searchId": "I - IV - vii° - iii - vi - ii - V - I"
    }
];

    const compositores = {
        "claudio-monteverdi": [
                "I - V - I",
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - IV - I6/4 - V - I",
                "i - iv - V - i",
                "i - VI - ii°6 - V - i",
                "I - V/vi - vi - ii - V - I",
                "I - IV - vii°6/V - V - I",
                "I - iii - vi - ii - V - I",
                "i - iv6 - V/III - III",
                "I - V/V - V - I",
                "I - ii - V/V - V - I",
                "I - IV - ii6 - V - I",
                "i - VII - III - iv - V - i"
        ],
        "jean-baptiste-lully": [
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - IV - I - V",
                "i - iv - V - i",
                "I - vi - ii6 - V - I",
                "I - IV - vii°6/V - V - I",
                "I - V/V - V - I",
                "i - VI - iv6 - V - i",
                "I - IV - I6/4 - V - I",
                "I - iii - IV - V - I",
                "i - iv - VII - III",
                "I - ii - V - I",
                "I - IV - ii - V - I",
                "I - vi - IV - V - I",
                "I - V - IV - V - I"
        ],
        "henry-purcell": [
                "i - VII - VI - V",
                "i - v6 - VI - III - iv6 - i6/4 - V - i",
                "i - iv - V - i",
                "I - V - vi - iii - IV - I - ii - V",
                "i - VI - III - VII",
                "i - iv6 - i6/4 - V - i",
                "I - IV - I - V",
                "i - VII - III - VII",
                "i - v - VI - V",
                "I - iii - IV - I - ii - V - I",
                "i - iv - i6 - V",
                "i - VI - iv - V",
                "I - IV - ii6 - V - I",
                "i - VII - VI - V - i",
                "I - V/V - V - I"
        ],
        "arcangelo-corelli": [
                "I - V - I",
                "I - IV - V - I",
                "I - V/ii - ii - V - I",
                "I - iii - vi - ii - V - I",
                "i - iv - V - i",
                "I - V/V - V - I",
                "I - vi - ii - V - I",
                "i - VI - III - iv - V - i",
                "I - IV - vii°6/V - V - I",
                "I - ii6 - V - I",
                "I - I6/4 - V - I",
                "I - IV - I - V",
                "i - iv6 - V/III - III",
                "I - V/vi - vi - IV - V - I",
                "I - ii - V/V - V - I"
        ],
        "johann-pachelbel": [
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - IV - I6/4 - V - I",
                "i - iv6 - V - i",
                "I - vi - ii6 - V - I",
                "I - iii - IV - I - ii - V - I",
                "I - V/V - V - I",
                "i - VI - ii°6 - V - i",
                "I - IV - vii°6/V - V - I",
                "I - ii - V - I",
                "I - IV - ii - V - I",
                "i - iv - VII - III",
                "I - vi - IV - V - I",
                "I - I6 - IV - V - I",
                "i - V/iv - iv - V - i"
        ],
        "francois-couperin": [
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - IV - I - V",
                "i - iv - V - i",
                "I - vi - ii6 - V - I",
                "I - IV - vii°6/V - V - I",
                "I - V/V - V - I",
                "i - VI - iv6 - V - i",
                "I - IV - I6/4 - V - I",
                "I - iii - IV - V - I",
                "i - iv - VII - III",
                "I - ii - V - I",
                "I - IV - ii - V - I",
                "I - vi - IV - V - I",
                "I - V - IV - V - I"
        ],
        "antonio-vivaldi": [
                "I - V - I",
                "I - IV - V - I",
                "I - V/ii - ii - V - I",
                "I - iii - vi - ii - V - I",
                "i - iv - V - i",
                "I - V/V - V - I",
                "I - vi - ii - V - I",
                "i - VI - III - iv - V - i",
                "I - IV - vii°6/V - V - I",
                "I - ii6 - V - I",
                "I - I6/4 - V - I",
                "I - IV - I - V",
                "i - iv6 - V/III - III",
                "I - V/vi - vi - IV - V - I",
                "I - ii - V/V - V - I"
        ],
        "georg-philipp-telemann": [
                "I - V - I",
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - IV - I6/4 - V - I",
                "i - iv - V - i",
                "i - VI - ii°6 - V - i",
                "I - V/vi - vi - ii - V - I",
                "I - IV - vii°6/V - V - I",
                "I - iii - vi - ii - V - I",
                "i - iv6 - V/III - III",
                "I - V/V - V - I",
                "I - ii - V/V - V - I",
                "I - IV - ii6 - V - I",
                "i - VII - III - iv - V - i"
        ],
        "jean-philippe-rameau": [
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - IV - I - V",
                "i - iv - V - i",
                "I - vi - ii6 - V - I",
                "I - IV - vii°6/V - V - I",
                "I - V/V - V - I",
                "i - VI - iv6 - V - i",
                "I - IV - I6/4 - V - I",
                "I - iii - IV - V - I",
                "i - iv - VII - III",
                "I - ii - V - I",
                "I - IV - ii - V - I",
                "I - vi - IV - V - I",
                "I - V - IV - V - I"
        ],
        "domenico-scarlatti": [
                "I - V - I",
                "I - V/V - V - I",
                "I - iii - vi - ii - V - I",
                "I - vi - ii - V - I",
                "I - IV - V - I",
                "i - VII - VI - V",
                "i - iv - V - i",
                "I - ♭VII - IV - I",
                "I - V - IV - I",
                "I - ii - V - I",
                "i - VI - III - VII",
                "I - IV - I6/4 - V - I",
                "I - V/vi - vi - V/V - V - I",
                "i - iv6 - i6/4 - V - i",
                "I - ♭III - ♭VII - I"
        ],
        "george-frideric-handel": [
                "I - IV - V - I",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "i - iv - V - i",
                "I - iii - vi - ii - V - I",
                "I - IV - I6/4 - V - I",
                "i - VI - ii°6 - V - i",
                "I - ii6 - V - I",
                "I - IV - vii°6/V - V - I",
                "I - V/ii - ii - V - I",
                "I - vi - IV - V - I",
                "i - VII - III - iv - V - i",
                "I - I - IV - V",
                "I - ii - V/V - V - I",
                "I - IV - ii - V - I"
        ],
        "johann-sebastian-bach": [
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - iii - vi - ii - V - I",
                "I - IV - vii°6/V - V - I",
                "i - iv6 - V - i",
                "i - VI - ii°6 - V - i",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "i - iv - VII - III",
                "I - I6 - IV - ii6 - V - I",
                "I - IV - I6/4 - V - I",
                "i - V/iv - iv - vii°7/V - V - i",
                "I - vi - IV - ii6 - V - I",
                "i - iv - i6/4 - V - i",
                "I - ♭II6 - V - I"
        ],
        "cpe-bach": [
                "I - V/vi - vi",
                "I - ii6 - V - I",
                "i - VI - iv - V - i",
                "I - IV - V/V - V - I",
                "I - iii - vi - IV",
                "i - iv6 - V/III - III",
                "I - vi - ii - V - I",
                "I - ♭VII - IV - I",
                "i - ii°6 - V - i",
                "I - IV - ii6 - V - I",
                "I - V - vi",
                "i - VI - III - iv - V - i",
                "I - V/V - V - I",
                "I - I6 - IV - V",
                "i - ♭II6 - V - i"
        ],
        "christoph-willibald-gluck": [
                "I - V - I",
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "i - iv - V - i",
                "I - I6/4 - V - I",
                "I - iii - IV - V - I",
                "I - IV - ii6 - V - I",
                "I - vi - IV - V - I",
                "I - ii - V - I",
                "i - VI - ii°6 - V - i",
                "I - IV - I - V",
                "I - V - vi - V",
                "I - ii - V/V - V - I"
        ],
        "luigi-boccherini": [
                "I - V - I",
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "i - iv - V - i",
                "I - I6/4 - V - I",
                "I - iii - IV - V - I",
                "I - IV - ii6 - V - I",
                "I - vi - IV - V - I",
                "I - ii - V - I",
                "i - VI - ii°6 - V - i",
                "I - IV - I - V",
                "I - V - vi - V",
                "I - ii - V/V - V - I"
        ],
        "muzio-clementi": [
                "I - V - I",
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "i - iv - V - i",
                "I - I6/4 - V - I",
                "I - iii - IV - V - I",
                "I - IV - ii6 - V - I",
                "I - vi - IV - V - I",
                "I - ii - V - I",
                "i - VI - ii°6 - V - i",
                "I - IV - I - V",
                "I - V - vi - V",
                "I - ii - V/V - V - I"
        ],
        "antonio-salieri": [
                "I - V - I",
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "i - iv - V - i",
                "I - I6/4 - V - I",
                "I - iii - IV - V - I",
                "I - IV - ii6 - V - I",
                "I - vi - IV - V - I",
                "I - ii - V - I",
                "i - VI - ii°6 - V - i",
                "I - IV - I - V",
                "I - V - vi - V",
                "I - ii - V/V - V - I"
        ],
        "joseph-haydn": [
                "I - IV - V - I",
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "I - I6 - ii6 - V - I",
                "i - iv - V - i",
                "I - IV - I6/4 - V - I",
                "I - ♭VII - IV - I",
                "I - iii - vi - ii - V - I",
                "I - IV - ii - V - I",
                "I - V - vi",
                "i - VI - iv - V - i",
                "I - ii - V - I",
                "I - V/ii - ii - V - I",
                "I - IV - V/V - V - I"
        ],
        "wolfgang-amadeus-mozart": [
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "I - IV - ii6 - V - I",
                "I - I6/4 - V - I",
                "i - iv6 - V - i",
                "I - iii - vi - ii - V - I",
                "I - IV - V - I",
                "I - V - vi",
                "i - VI - ii°6 - V - i",
                "I - IV - iv - I",
                "I - ♭II6 - V - I",
                "I - V/vi - vi - ii - V - I",
                "I - ii - V/V - V - I",
                "I - I6 - IV - V - I"
        ],
        "luigi-cherubini": [
                "I - V/V - V - I",
                "I - iii - vi - ii - V - I",
                "I - ♭VI - V",
                "i - VI - iv - V - i",
                "I - IV - ii - V - I",
                "I - ii6 - V - I",
                "I - ♭II6 - V - I",
                "I - vi - IV - V - I",
                "i - VII - VI - V",
                "I - mediant ♭III - vi - ii - V - I",
                "I - V - vi",
                "i - iv - i6/4 - V - i",
                "I - IV - I6/4 - V - I",
                "I - V/ii - ii - V/V - V - I",
                "I - iii - IV - iv - I"
        ],
        "ludwig-van-beethoven": [
                "I - V/V - V - I",
                "I - iii - vi - ii - V - I",
                "I - ♭VI - V",
                "i - VI - iv - V - i",
                "I - IV - ii - V - I",
                "I - ii6 - V - I",
                "I - ♭II6 - V - I",
                "I - vi - IV - V - I",
                "i - VII - VI - V",
                "I - mediant ♭III - vi - ii - V - I",
                "I - V - vi",
                "i - iv - i6/4 - V - i",
                "I - IV - I6/4 - V - I",
                "I - V/ii - ii - V/V - V - I",
                "I - iii - IV - iv - I"
        ],
        "franz-schubert": [
                "I - vi - IV - V - I",
                "I - ♭III - ♭VI - V",
                "i - VI - III - VII",
                "I - iii - vi - IV",
                "i - iv - VI - V - i",
                "I - V/vi - vi - ii - V - I",
                "I - IV - ii6 - V - I",
                "i - VI - iv - V - i",
                "I - ♭VI - ♭VII - I",
                "I - I6 - IV - V - I",
                "i - III - VI - iiø6/5 - V - i",
                "I - V - vi",
                "I - ii - V/V - V - I",
                "i - ♭II6 - V - i",
                "I - ♭III - IV - iv - I"
        ],
        "gioachino-rossini": [
                "I - V - I",
                "I - IV - V - I",
                "I - V/V - V - I",
                "I - vi - ii - V - I",
                "I - I6/4 - V - I",
                "i - iv - V - i",
                "I - IV - ii6 - V - I",
                "I - V/ii - ii - V - I",
                "I - iii - vi - ii - V - I",
                "I - V - vi - V",
                "i - VI - III - iv - V - i",
                "I - ♭VII - IV - I",
                "I - IV - I - V",
                "I - ii - V/V - V - I",
                "I - vi - IV - V - I"
        ],
        "vincenzo-bellini": [
                "I - V - I",
                "I - ii6 - V - I",
                "I - vi - ii - V - I",
                "I - IV - V - I",
                "i - VI - iv - V - i",
                "I - V/V - V - I",
                "I - IV - ii6 - V - I",
                "I - V - vi",
                "i - iv6 - V - i",
                "I - iii - vi - IV",
                "I - I6 - IV - V - I",
                "i - ♭VII - VI - V",
                "I - vi - IV - V - I",
                "I - ii - V - I",
                "I - ♭II6 - V - I"
        ],
        "gaetano-donizetti": [
                "I - V/V - V - I",
                "I - IV - V - I",
                "I - vi - ii - V - I",
                "I - ii6 - V - I",
                "i - iv - V - i",
                "I - V - vi - V",
                "I - IV - ii - V - I",
                "I - I6/4 - V - I",
                "I - iii - vi - ii - V - I",
                "i - VI - III - iv - V - i",
                "I - V/ii - ii - V - I",
                "I - vi - IV - V - I",
                "I - IV - I - V",
                "i - ♭II6 - V - i",
                "I - ii - V/V - V - I"
        ],
        "carl-maria-von-weber": [
                "I - V/V - V - I",
                "I - IV - V - I",
                "I - vi - ii - V - I",
                "I - ii6 - V - I",
                "i - iv - V - i",
                "I - V - vi - V",
                "I - IV - ii - V - I",
                "I - I6/4 - V - I",
                "I - iii - vi - ii - V - I",
                "i - VI - III - iv - V - i",
                "I - V/ii - ii - V - I",
                "I - vi - IV - V - I",
                "I - IV - I - V",
                "i - ♭II6 - V - i",
                "I - ii - V/V - V - I"
        ],
        "felix-mendelssohn": [
                "I - vi - IV - V - I",
                "I - iii - vi - IV",
                "I - V/vi - vi - ii - V - I",
                "i - VI - iv - V - i",
                "I - IV - ii6 - V - I",
                "I - V - vi",
                "I - ♭VI - ♭VII - I",
                "i - III - VI - iiø - V - i",
                "I - ii - V/V - V - I",
                "I - IV - iv - I",
                "I - I6 - IV - V - I",
                "i - ♭II6 - V - i",
                "I - iii - ♭III - IV",
                "I - IV - I6/4 - V - I",
                "i - VII - VI - V"
        ],
        "robert-schumann": [
                "I - vi - IV - V - I",
                "I - iii - vi - IV",
                "I - V/vi - vi - ii - V - I",
                "i - VI - iv - V - i",
                "I - IV - ii6 - V - I",
                "I - V - vi",
                "I - ♭VI - ♭VII - I",
                "i - III - VI - iiø - V - i",
                "I - ii - V/V - V - I",
                "I - IV - iv - I",
                "I - I6 - IV - V - I",
                "i - ♭II6 - V - i",
                "I - iii - ♭III - IV",
                "I - IV - I6/4 - V - I",
                "i - VII - VI - V"
        ],
        "frederic-chopin": [
                "i - iv6 - V - i",
                "I - V/vi - vi - iiø7 - V - I",
                "i - VI - III - iv - V - i",
                "I - ♭II6 - V - I",
                "I - iii - vi - ii - V - I",
                "i - vii°7/V - V - i",
                "I - IV - iv - I",
                "I - V - vi",
                "i - ♭VI - V",
                "I - mediant ♭III - ♭VI - V",
                "i - iiø6/5 - V7 - i",
                "I - vi - IV - ii - V - I",
                "I - augmented-sixth - V - I",
                "i - I7 - iv",
                "I - ♭III - ♭VII - I"
        ],
        "hector-berlioz": [
                "I - ♭VI - V",
                "i - VI - III - VII",
                "I - iii - ♭III - IV",
                "I - V/V - V - I",
                "i - ♭II6 - V - i",
                "I - mediant ♭III - ♭VI",
                "i - iv - V - i",
                "I - IV - ii - V - I",
                "I - ♭VII - IV - I",
                "i - vii°7/V - V - i",
                "I - vi - IV - V - I",
                "I - augmented-sixth - V - I",
                "i - III - ♭VI - V",
                "I - ♭III - IV - iv - I",
                "I - ii - V/V - V - I"
        ],
        "franz-liszt": [
                "i - iv6 - V - i",
                "I - V/vi - vi - iiø7 - V - I",
                "i - VI - III - iv - V - i",
                "I - ♭II6 - V - I",
                "I - iii - vi - ii - V - I",
                "i - vii°7/V - V - i",
                "I - IV - iv - I",
                "I - V - vi",
                "i - ♭VI - V",
                "I - mediant ♭III - ♭VI - V",
                "i - iiø6/5 - V7 - i",
                "I - vi - IV - ii - V - I",
                "I - augmented-sixth - V - I",
                "i - I7 - iv",
                "I - ♭III - ♭VII - I"
        ],
        "mikhail-glinka": [
                "i - VI - III - VII",
                "i - iv - V - i",
                "i - ♭VII - ♭VI - V",
                "I - ♭III - IV - I",
                "I - vi - IV - V - I",
                "i - ii°6 - V - i",
                "I - IV - ii - V - I",
                "i - III - VI - iiø - V - i",
                "I - V/V - V - I",
                "i - iv - i6/4 - V - i",
                "I - ♭VI - ♭VII - I",
                "i - V/III - III",
                "I - IV - iv - I",
                "i - ♭II6 - V - i",
                "I - iii - vi - ii - V - I"
        ],
        "richard-wagner": [
                "i - ♭II6 - V",
                "i - vii°7/V - V - deceptive",
                "I - mediant ♭III - ♭VI - V",
                "i - iv - Ger+6 - V",
                "I - V/V - V - I",
                "i - VI - III - iv",
                "I - IV - iv - I",
                "i - iiø7 - V7 - i",
                "I - ♭VI - ♭VII - I",
                "i - V/iv - iv - V",
                "I - augmented-sixth - V",
                "i - ♭III - ♭II6 - V",
                "I - tritone-related dominant - I",
                "i - VI - ♭II6 - V",
                "I - V - vi"
        ],
        "giuseppe-verdi": [
                "I - V/V - V - I",
                "I - IV - V - I",
                "I - vi - ii - V - I",
                "i - iv - V - i",
                "I - IV - ii6 - V - I",
                "I - I6/4 - V - I",
                "I - V - vi - V",
                "i - ♭II6 - V - i",
                "I - iii - vi - ii - V - I",
                "I - vi - IV - V - I",
                "i - VI - III - iv - V - i",
                "I - IV - I - V",
                "I - ii - V/V - V - I",
                "I - ♭VI - V",
                "I - IV - iv - I"
        ],
        "johannes-brahms": [
                "I - vi - ii - V - I",
                "I - iii - vi - ii - V - I",
                "I - IV - ii - V - I",
                "i - VI - iv - V - i",
                "I - ♭III - vi - IV",
                "I - IV - iv - I",
                "I - ii6 - V - I",
                "i - iiø - V - i",
                "I - V - vi",
                "I - I6 - IV - ii6 - V - I",
                "I - ♭VI - V",
                "i - III - VI - iiø - V - i",
                "I - V/V - V - I",
                "I - IV - I6/4 - V - I",
                "i - ♭II6 - V - i"
        ],
        "anton-bruckner": [
                "I - IV - I - V - I",
                "I - ii6 - V - I",
                "i - iv - V - i",
                "I - ♭VI - ♭VII - I",
                "I - IV - ii - V - I",
                "I - V/V - V - I",
                "i - VI - III - iv - V - i",
                "I - I6/4 - V - I",
                "I - IV - iv - I",
                "i - ♭II6 - V - i",
                "I - iii - vi - ii - V - I",
                "i - iv - i6/4 - V - i",
                "I - V - vi",
                "I - plagal IV - I",
                "I - IV - V/V - V - I"
        ],
        "camille-saint-saëns": [
                "I - vi - IV - V - I",
                "I - iii - vi - IV",
                "I - V/vi - vi - ii - V - I",
                "i - VI - iv - V - i",
                "I - IV - ii6 - V - I",
                "I - V - vi",
                "I - ♭VI - ♭VII - I",
                "i - III - VI - iiø - V - i",
                "I - ii - V/V - V - I",
                "I - IV - iv - I",
                "I - I6 - IV - V - I",
                "i - ♭II6 - V - i",
                "I - iii - ♭III - IV",
                "I - IV - I6/4 - V - I",
                "i - VII - VI - V"
        ],
        "cesar-franck": [
                "I - vi - ii - V - I",
                "I - iii - vi - ii - V - I",
                "I - IV - iv - I",
                "i - VI - iv - V - i",
                "I - ♭III - ♭VI - V",
                "I - ii6 - V - I",
                "I - IV - ii - V - I",
                "i - ♭II6 - V - i",
                "I - V/V - V - I",
                "I - I6 - IV - V - I",
                "i - III - VI - iiø - V - i",
                "I - plagal IV - I",
                "I - ♭VI - ♭VII - I",
                "i - iv - i6/4 - V - i",
                "I - vi - IV - V - I"
        ],
        "bedrich-smetana": [
                "I - ♭VII - IV - I",
                "i - VII - VI - V",
                "I - vi - IV - V - I",
                "i - VI - III - VII",
                "I - IV - V - I",
                "i - iv - V - i",
                "I - ♭III - IV - I",
                "I - ii - V - I",
                "I - IV - iv - I",
                "i - V/III - III",
                "I - V/V - V - I",
                "i - ♭II6 - V - i",
                "I - I6 - IV - V - I",
                "I - iii - vi - ii - V - I",
                "I - ♭VI - ♭VII - I"
        ],
        "antonin-dvorak": [
                "I - ♭VII - IV - I",
                "i - VII - VI - V",
                "I - vi - IV - V - I",
                "i - VI - III - VII",
                "I - IV - V - I",
                "i - iv - V - i",
                "I - ♭III - IV - I",
                "I - ii - V - I",
                "I - IV - iv - I",
                "i - V/III - III",
                "I - V/V - V - I",
                "i - ♭II6 - V - i",
                "I - I6 - IV - V - I",
                "I - iii - vi - ii - V - I",
                "I - ♭VI - ♭VII - I"
        ],
        "edvard-grieg": [
                "I - ♭VII - IV - I",
                "i - VII - VI - V",
                "I - vi - IV - V - I",
                "i - VI - III - VII",
                "I - IV - V - I",
                "i - iv - V - i",
                "I - ♭III - IV - I",
                "I - ii - V - I",
                "I - IV - iv - I",
                "i - V/III - III",
                "I - V/V - V - I",
                "i - ♭II6 - V - i",
                "I - I6 - IV - V - I",
                "I - iii - vi - ii - V - I",
                "I - ♭VI - ♭VII - I"
        ],
        "modest-mussorgsky": [
                "i - VII - VI - V",
                "i - ♭VII - i",
                "i - VI - III - VII",
                "I - ♭III - ♭II - I",
                "i - iv - V - i",
                "I - ♭VII - IV - I",
                "i - ♭VI - ♭VII - i",
                "I - pedal I - IV",
                "i - V/III - III",
                "i - iv - i",
                "I - II - ♭II - I",
                "i - ♭II6 - V - i",
                "I - plagal IV - I",
                "i - VII - III - iv",
                "I - V/V - V - I"
        ],
        "alexander-borodin": [
                "i - VI - III - VII",
                "i - iv - V - i",
                "i - ♭VII - ♭VI - V",
                "I - ♭III - IV - I",
                "I - vi - IV - V - I",
                "i - ii°6 - V - i",
                "I - IV - ii - V - I",
                "i - III - VI - iiø - V - i",
                "I - V/V - V - I",
                "i - iv - i6/4 - V - i",
                "I - ♭VI - ♭VII - I",
                "i - V/III - III",
                "I - IV - iv - I",
                "i - ♭II6 - V - i",
                "I - iii - vi - ii - V - I"
        ],
        "nikolai-rimsky-korsakov": [
                "i - VI - III - VII",
                "i - iv - V - i",
                "i - ♭VII - ♭VI - V",
                "I - ♭III - IV - I",
                "I - vi - IV - V - I",
                "i - ii°6 - V - i",
                "I - IV - ii - V - I",
                "i - III - VI - iiø - V - i",
                "I - V/V - V - I",
                "i - iv - i6/4 - V - i",
                "I - ♭VI - ♭VII - I",
                "i - V/III - III",
                "I - IV - iv - I",
                "i - ♭II6 - V - i",
                "I - iii - vi - ii - V - I"
        ],
        "pyotr-ilyich-tchaikovsky": [
                "i - VI - III - VII",
                "I - vi - IV - V - I",
                "i - iv - V - i",
                "I - IV - ii6 - V - I",
                "I - V/V - V - I",
                "i - ♭II6 - V - i",
                "I - iii - vi - IV",
                "i - VI - iv - V - i",
                "I - IV - iv - I",
                "I - V - vi",
                "i - III - VI - iiø - V - i",
                "I - ♭VI - ♭VII - I",
                "I - I6 - IV - V - I",
                "i - iv - i6/4 - V - i",
                "I - ii - V/V - V - I"
        ],
        "gustav-mahler": [
                "I - vi - IV - V - I",
                "I - ♭VI - ♭VII - I",
                "i - VI - III - VII",
                "I - IV - iv - I",
                "i - ♭II6 - V - i",
                "I - iii - vi - ii - V - I",
                "I - V/V - V - I",
                "i - iv - V - i",
                "I - pedal I - ♭VI",
                "I - tritone-related harmony - V - I",
                "i - III - ♭VI - V",
                "I - plagal IV - I",
                "I - V - vi",
                "i - VII - VI - V",
                "I - ii - V - I"
        ],
        "gabriel-faure": [
                "I - vi - IV - ii - V - I",
                "I - IV - iv - I",
                "I - ii6 - V - I",
                "I - iii - vi - IV",
                "i - VI - iv - V - i",
                "I - V/V - V - I",
                "I - add6 tonic - ii - V",
                "I - plagal IV - I",
                "i - ♭II6 - V - i",
                "I - vi - ii - V - I",
                "I - IV - ii - V - I",
                "I - V - vi",
                "I - ♭III - IV - I",
                "i - VII - VI - V",
                "I - I6 - IV - V - I"
        ],
        "claude-debussy": [
                "I(add2) - IV(add6) - I",
                "planing: ♭III - II - I",
                "quartal sonority - pedal I",
                "i - ♭VII - ♭VI - ♭VII",
                "I - II - I",
                "I - ♭II - I",
                "whole-tone collection around I",
                "I - V pedal with upper planing",
                "I - IV - ♭VII - I",
                "parallel 9th chords descending to I",
                "pentatonic I - ♭III - IV - I",
                "i - iv - i with added 6ths",
                "I - mediant III - II - I",
                "I - plagal IV - I",
                "I - unresolved dominant sonority - I color"
        ],
        "erik-satie": [
                "I - IV - I",
                "I - ♭VII - I",
                "i - VII - i",
                "I - II - I",
                "parallel triads over pedal I",
                "I - IV(add6) - I",
                "I - iii - IV - I",
                "i - ♭VI - ♭VII - i",
                "I - plagal IV - I",
                "I - V - I",
                "I - ♭III - I",
                "i - iv - i",
                "I - II - ♭II - I",
                "I - VI - I",
                "pedal I with modal upper neighbors"
        ],
        "maurice-ravel": [
                "I - vi - ii - V - I",
                "I - IV - iv - I",
                "I - ♭II - I",
                "planing 7ths toward I",
                "I - V/V - V - I",
                "I - mediant ♭III - IV",
                "i - VI - iv - V - i",
                "extended tonic - ii - V - I",
                "I - ♭VI - ♭VII - I",
                "I - add6 tonic - IV - I",
                "i - ♭II6 - V - i",
                "whole-tone dominant to tonic color",
                "I - plagal IV - I",
                "I - iii - vi - IV",
                "bitonal upper structure over tonic pedal"
        ],
        "sergei-rachmaninoff": [
                "i - VI - III - VII",
                "I - vi - IV - V - I",
                "i - iv - V - i",
                "I - iii - vi - ii - V - I",
                "i - ♭II6 - V - i",
                "I - V/V - V - I",
                "i - VI - iv - V - i",
                "I - IV - ii - V - I",
                "I - V - vi",
                "i - III - VI - iiø - V - i",
                "I - ♭VI - ♭VII - I",
                "i - iv - i6/4 - V - i",
                "I - IV - iv - I",
                "I - I6 - IV - V - I",
                "i - vii°7/V - V - i"
        ],
        "alexander-scriabin": [
                "I - altered dominant - I",
                "I - ♭II - V - I",
                "mystic-chord field around tonic",
                "I - augmented-sixth - V",
                "I - mediant ♯III - VI",
                "i - tritone dominant - i",
                "I - V/V - V - I",
                "I - whole-tone dominant field - I",
                "I - IV - ♯IV° - V",
                "i - VI - ♭II - V",
                "I - planed dominant sonorities - I",
                "I - ♭VI - V",
                "I - add6/add9 tonic - altered predominant",
                "i - iv - altered V - i",
                "I - mediant relations chain"
        ],
        "jean-sibelius": [
                "i - VII - VI - V",
                "I - IV - I",
                "I - ♭VII - IV - I",
                "i - VI - III - VII",
                "I - V/V - V - I",
                "I - pedal I - IV",
                "i - iv - V - i",
                "I - ♭VI - ♭VII - I",
                "I - ii - V - I",
                "I - IV - iv - I",
                "i - V/III - III",
                "I - plagal IV - I",
                "I - iii - IV - I",
                "i - ♭II6 - V - i",
                "pedal dominant with modal upper motion"
        ],
        "edward-elgar": [
                "I - IV - V - I",
                "I - vi - ii - V - I",
                "I - V/V - V - I",
                "i - iv - V - i",
                "I - IV - ii - V - I",
                "I - plagal IV - I",
                "I - I6 - IV - V - I",
                "I - ♭VI - ♭VII - I",
                "i - ♭II6 - V - i",
                "I - iii - vi - IV",
                "I - IV - iv - I",
                "I - V - vi",
                "i - VI - iv - V - i",
                "I - ii - V/V - V - I",
                "I - mediant ♭III - IV - I"
        ],
        "leoš-janaček": [
                "i - VII - i",
                "I - ♭VII - IV - I",
                "I - II - I",
                "i - iv - i",
                "I - IV - I",
                "i - VI - VII - i",
                "I - ♭III - II - I",
                "pedal I with changing upper dyads",
                "i - ♭II - i",
                "I - V - I",
                "i - iv - V - i",
                "I - ♭VI - ♭VII - I",
                "I - IV - ♭VII - I",
                "I - tritone-related upper block over pedal",
                "i - V/III - III"
        ],
        "ottorino-respighi": [
                "I - IV - V - I",
                "I - ♭VII - IV - I",
                "i - VI - III - VII",
                "I - vi - ii - V - I",
                "I - plagal IV - I",
                "i - iv - V - i",
                "I - V/V - V - I",
                "I - IV - iv - I",
                "i - ♭II6 - V - i",
                "I - I6 - IV - V - I",
                "I - ♭VI - ♭VII - I",
                "i - iv - i6/4 - V - i",
                "I - iii - vi - IV",
                "I - II - I",
                "pedal dominant with modal upper chords"
        ],
        "manuel-de-falla": [
                "i - ♭VII - ♭VI - V",
                "i - II - I",
                "I - ♭VII - IV - I",
                "i - iv - V - i",
                "i - ♭II - I",
                "I - pedal V with Phrygian upper motion",
                "i - VI - III - VII",
                "I - IV - iv - I",
                "I - V/V - V - I",
                "i - ♭VI - ♭VII - i",
                "I - ♭III - II - I",
                "i - iv - i",
                "I - plagal IV - I",
                "I - iii - IV - I",
                "i - ♭II6 - V - i"
        ],
        "bela-bartok": [
                "axis tonic - axis dominant - axis tonic",
                "I - ♭II - I",
                "pedal tonic with quartal blocks",
                "i - VII - i",
                "I - tritone pole - I",
                "i - IV - i",
                "I - ♭VI - ♭VII - I",
                "I - II - I",
                "I - V - I",
                "octatonic collection around tonic",
                "I - ♭III - ♭II - I",
                "pedal dominant with polymodal upper chords",
                "i - v - i",
                "I - IV - ♯IV - V",
                "clustered predominant - tonic"
        ],
        "igor-stravinsky": [
                "tonic pedal + upper dominant block",
                "I - ♭II - I",
                "ostinato on I with shifting triads",
                "I - tritone-related block - I",
                "I - ♭VII - IV - I",
                "i - VII - i",
                "polychord over tonic pedal",
                "I - V - I",
                "I - II - I",
                "octatonic dominant field - tonic block",
                "I - IV - I",
                "i - ♭VI - ♭VII - i",
                "I - iii - IV - I",
                "I - secondary dominant - V - I",
                "parallel dominant blocks to tonic"
        ],
        "francis-poulenc": [
                "I - vi - ii - V - I",
                "I - IV - iv - I",
                "I - ♭III - IV - I",
                "I - V/V - V - I",
                "I(add6) - ii - V - I",
                "i - VI - iv - V - i",
                "I - iii - vi - IV",
                "I - ♭II - I",
                "I - V - vi",
                "I - plagal IV - I",
                "parallel 7th/9th chords toward I",
                "I - ii6 - V - I",
                "I - ♭VI - ♭VII - I",
                "i - ♭II6 - V - i",
                "I - extended tonic - altered predominant - V - I"
        ]
};

    return {
        basicas,
        compositores
    };
})();

if (typeof window !== "undefined") window.PROGRESIONES_DATA = PROGRESIONES_DATA;
